/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  async rewrites() {
    return [
      {
        source: '/sitemap.xml',
        destination: '/api/sitemap',
      },
    ]
  },
  i18n: {
    // providing the locales supported by your application
    locales: [
      'am',
      'ar',
      'bg',
      'bn',
      'ca',
      'cs',
      'da',
      'de',
      'el',
      'en',
      'en_GB',
      'en_US',
      'es',
      'es_419',
      'et',
      'fa',
      'fi',
      'fil',
      'fr',
      'gu',
      'he',
      'hi',
      'hr',
      'hu',
      'id',
      'it',
      'ja',
      'kn',
      'ko',
      'lt',
      'lv',
      'ml',
      'mr',
      'ms',
      'nl',
      'no',
      'pl',
      'pt_BR',
      'pt_PT',
      'ro',
      'ru',
      'sk',
      'sl',
      'sr',
      'sv',
      'sw',
      'ta',
      'te',
      'th',
      'tr',
      'uk',
      'vi',
      'zh_CN',
      'zh_TW',
    ],
    //  default locale used when the non-locale paths are visited
    defaultLocale: 'en',
  },
}
